from __future__ import annotations

import hashlib
import hmac
import html
import logging
import os
from datetime import datetime
from zoneinfo import ZoneInfo

from reactiva.campaigns.status import (
    normalize_customer_status,
    set_customer_opt_out,
)
from reactiva.campaigns.storage import (
    CUSTOMER_CAMPAIGN_STATUS_KEY,
    read_csv_from_s3,
    write_csv_to_s3,
)
from reactiva.config import (
    S3_BUCKET,
)


# ============================================================
# CONFIGURATION
# ============================================================

BUSINESS_TIMEZONE = "Asia/Kolkata"

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


# ============================================================
# ENVIRONMENT
# ============================================================

def _get_unsubscribe_secret() -> str:
    """
    Reads the private HMAC secret used to validate unsubscribe links.

    The secret must exist only in the Lambda environment and must
    never be committed to the repository.
    """
    secret = os.getenv(
        "UNSUBSCRIBE_SECRET"
    )

    if (
        secret is None
        or not secret.strip()
    ):
        raise RuntimeError(
            "UNSUBSCRIBE_SECRET environment variable "
            "is required"
        )

    return secret.strip()


# ============================================================
# TOKEN
# ============================================================

def build_unsubscribe_token(
    customer_id: str,
    campaign_id: str,
    secret: str,
) -> str:
    """
    Creates a deterministic HMAC token for one customer/campaign.

    The same algorithm must be used when the email unsubscribe
    URL is generated by the campaign sender.
    """
    customer_id = str(
        customer_id
    ).strip()

    campaign_id = str(
        campaign_id
    ).strip()

    if not customer_id:
        raise ValueError(
            "customer_id is required"
        )

    if not campaign_id:
        raise ValueError(
            "campaign_id is required"
        )

    if not secret:
        raise ValueError(
            "secret is required"
        )

    message = (
        f"{campaign_id}:{customer_id}"
    ).encode(
        "utf-8"
    )

    return hmac.new(
        secret.encode(
            "utf-8"
        ),
        message,
        hashlib.sha256,
    ).hexdigest()


def validate_unsubscribe_token(
    customer_id: str,
    campaign_id: str,
    token: str,
    secret: str,
) -> bool:
    """
    Validates an unsubscribe token using constant-time comparison.
    """
    if (
        token is None
        or not str(token).strip()
    ):
        return False

    expected_token = (
        build_unsubscribe_token(
            customer_id=customer_id,
            campaign_id=campaign_id,
            secret=secret,
        )
    )

    return hmac.compare_digest(
        expected_token,
        str(token).strip(),
    )


# ============================================================
# HTTP RESPONSE
# ============================================================

def _html_response(
    status_code: int,
    title: str,
    message: str,
) -> dict:
    """
    Creates the HTML response returned by Lambda Function URL.
    """
    safe_title = html.escape(
        title
    )

    safe_message = html.escape(
        message
    )

    body = f"""<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
    >
    <title>{safe_title}</title>
</head>
<body>
    <main>
        <h1>{safe_title}</h1>
        <p>{safe_message}</p>
    </main>
</body>
</html>
"""

    return {
        "statusCode":
            int(
                status_code
            ),
        "headers": {
            "Content-Type":
                "text/html; charset=utf-8",
            "Cache-Control":
                "no-store",
        },
        "body":
            body,
    }


# ============================================================
# QUERY PARAMETERS
# ============================================================

def _get_query_parameters(
    event,
) -> tuple[str, str, str]:
    """
    Extracts and validates the required Function URL parameters.

    Required:
        customer_id
        campaign_id
        token
    """
    event = (
        event
        if isinstance(
            event,
            dict,
        )
        else {}
    )

    params = (
        event.get(
            "queryStringParameters"
        )
        or {}
    )

    customer_id = str(
        params.get(
            "customer_id",
            ""
        )
    ).strip()

    campaign_id = str(
        params.get(
            "campaign_id",
            ""
        )
    ).strip()

    token = str(
        params.get(
            "token",
            ""
        )
    ).strip()

    if (
        not customer_id
        or not campaign_id
        or not token
    ):
        raise ValueError(
            "Missing unsubscribe parameters"
        )

    return (
        customer_id,
        campaign_id,
        token,
    )


# ============================================================
# PERSISTENCE
# ============================================================

def _persist_opt_out(
    customer_id: str,
    bucket: str = S3_BUCKET,
    s3_client=None,
):
    """
    Marks the customer as OPT_OUT and persists the updated
    customer campaign status file.

    The operation is idempotent:
    clicking the same valid unsubscribe link more than once
    keeps the customer unsubscribed.
    """
    if not bucket:
        raise RuntimeError(
            "S3_BUCKET is required"
        )

    customer_status_df = (
        read_csv_from_s3(
            bucket=bucket,
            key=
                CUSTOMER_CAMPAIGN_STATUS_KEY,
            s3_client=s3_client,
        )
    )

    customer_status_df = (
        normalize_customer_status(
            customer_status_df
        )
    )

    india_now = datetime.now(
        ZoneInfo(
            BUSINESS_TIMEZONE
        )
    )

    updated_status_df = (
        set_customer_opt_out(
            customer_status_df=
                customer_status_df,
            customer_id=
                customer_id,
            opt_out_date=
                india_now,
        )
    )

    write_csv_to_s3(
        df=updated_status_df,
        bucket=bucket,
        key=
            CUSTOMER_CAMPAIGN_STATUS_KEY,
        s3_client=s3_client,
    )

    # Read-after-write verification.
    verified_df = (
        read_csv_from_s3(
            bucket=bucket,
            key=
                CUSTOMER_CAMPAIGN_STATUS_KEY,
            s3_client=s3_client,
        )
    )

    verified_df = (
        normalize_customer_status(
            verified_df
        )
    )

    customer_rows = (
        verified_df[
            verified_df[
                "Customer ID"
            ].astype(str)
            == str(
                customer_id
            )
        ]
    )

    if customer_rows.empty:
        raise RuntimeError(
            "Unsubscribe verification failed: "
            "customer status was not persisted"
        )

    opt_out_value = (
        customer_rows
        .iloc[-1][
            "Opt Out"
        ]
    )

    if not bool(
        opt_out_value
    ):
        raise RuntimeError(
            "Unsubscribe verification failed: "
            "Opt Out is not active"
        )

    return verified_df


# ============================================================
# LAMBDA HANDLER
# ============================================================

def lambda_handler(
    event,
    context,
):
    """
    Handles an unsubscribe request from a Lambda Function URL.

    Expected URL parameters:

        ?customer_id=CUST000001
        &campaign_id=REACTIVA-2026-09
        &token=<HMAC>

    Security:
        Customer ID and Campaign ID alone are not sufficient.
        A valid HMAC token generated with UNSUBSCRIBE_SECRET
        is mandatory.
    """
    request_id = (
        getattr(
            context,
            "aws_request_id",
            None,
        )
        if context is not None
        else None
    )

    try:
        (
            customer_id,
            campaign_id,
            token,
        ) = _get_query_parameters(
            event
        )

    except ValueError:
        logger.warning(
            "Invalid unsubscribe request "
            "request_id=%s",
            request_id,
        )

        return _html_response(
            status_code=400,
            title="Enlace inválido",
            message=(
                "El enlace de baja no es válido "
                "o está incompleto."
            ),
        )

    try:
        secret = (
            _get_unsubscribe_secret()
        )

        token_is_valid = (
            validate_unsubscribe_token(
                customer_id=
                    customer_id,
                campaign_id=
                    campaign_id,
                token=
                    token,
                secret=
                    secret,
            )
        )

        if not token_is_valid:
            logger.warning(
                "Invalid unsubscribe token "
                "customer=%s campaign=%s "
                "request_id=%s",
                customer_id,
                campaign_id,
                request_id,
            )

            return _html_response(
                status_code=403,
                title="Enlace inválido",
                message=(
                    "No fue posible validar "
                    "el enlace de baja."
                ),
            )

        _persist_opt_out(
            customer_id=
                customer_id,
        )

        logger.info(
            "Customer unsubscribed "
            "customer=%s campaign=%s "
            "request_id=%s",
            customer_id,
            campaign_id,
            request_id,
        )

        return _html_response(
            status_code=200,
            title="Baja confirmada",
            message=(
                "Tu baja de las campañas de "
                "ReActiva fue registrada correctamente."
            ),
        )

    except Exception:
        logger.exception(
            "Unsubscribe processing failed "
            "customer=%s campaign=%s "
            "request_id=%s",
            customer_id,
            campaign_id,
            request_id,
        )

        return _html_response(
            status_code=500,
            title="No pudimos procesar la solicitud",
            message=(
                "Ocurrió un error temporal. "
                "Por favor, intentá nuevamente más tarde."
            ),
        )