table DimFecha
	lineageTag: 6b58b10b-01b8-460e-aea6-f7361c0aba38

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d94855f4-7b76-467a-aed7-2ea25e058639
		summarizeBy: none
		sourceColumn: date

		variation Variación
			isDefault
			relationship: e97ee298-e798-4b08-b216-9ab5d216b030
			defaultHierarchy: LocalDateTable_bfe2907f-e45e-42d2-a30e-d96145aab140.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column day_name
		dataType: string
		lineageTag: a242e671-ef2f-43d5-8f47-c78acf26c61a
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: a33bcbae-7840-4b0a-bd23-7751fcd82261
		summarizeBy: sum
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: e63070c7-bfa3-45c9-9ab3-2c0766d7e998
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: 7264905f-738f-4640-8973-37eaa1de08c3
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: d48df665-b5c8-45ec-b3c5-b29981a42298
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column day_of_week_number
		dataType: int64
		formatString: 0
		lineageTag: 21655f50-41bd-462b-a653-3c3a52c6a7b4
		summarizeBy: sum
		sourceColumn: day_of_week_number

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		lineageTag: 04466b6c-6ba1-441a-b6f5-5c0e4b678bb7
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column season
		dataType: string
		lineageTag: d33ca86b-fb0a-4c89-80cd-5a8dd16f7078
		summarizeBy: none
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	partition DimFecha = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents(RutaDatosBI & "\bi_calendar.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type date}, {"day", Int64.Type}, {"day_of_week_number", Int64.Type}, {"day_name", type text}, {"season", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"year_month"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

